---
- hosts: ubuntu
  become: true

  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present 
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - docker-ce

    - name: Set permission to run a docker
      command: usermod -aG docker ubuntu

    - name: Enable docker and restart the service
      service:
        name: docker
        enabled: yes
        state: restarted

    - name: Check docker version
      command: docker --version
      register: docker

    - debug:
          msg: "{{ docker.stdout_lines|list }}"
